# Generated by Django 5.1.3 on 2024-11-26 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(default='Dice', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGameGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='small', max_length=30)),
                ('base_fee', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(default=None, max_length=30)),
                ('contact', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('capacity', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('boardgame_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('boardgame_name', models.CharField(default=None, max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_cafe.boardgamecategory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_cafe.boardgamegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(default=None, max_length=30)),
                ('item_id', models.CharField(default=None, max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_cafe.customer')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(default=None, max_length=30)),
                ('item_id', models.CharField(default=None, max_length=30)),
                ('rent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default=None, max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_game_cafe.customer')),
            ],
            options={
                'db_table': 'Rental',
            },
        ),
    ]
