# Generated by Django 5.1.3 on 2024-11-26 12:55

import board_game_cafe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='due_date',
            field=models.DateTimeField(default=board_game_cafe.models.next_three_days),
        ),
    ]
