# Generated by Django 5.1.3 on 2024-11-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_cafe', '0003_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
