# Generated by Django 5.1.3 on 2024-11-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_cafe', '0004_boardgame_stock_rental_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(default='rented', max_length=30),
        ),
    ]
