# Generated by Django 5.1.3 on 2024-11-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_cafe', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgamegroup',
            name='num_player',
            field=models.IntegerField(default=4),
        ),
    ]
