# Generated by Django 5.1.3 on 2024-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_game_cafe', '0008_alter_boardgamegroup_num_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rentable_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
